// order of transitions in demo video
export const transitions = [
	"Swirl",
	"Directional warp",
	"Hexagonalize",
	"Wipe down",
	"Radial",
	"Crosswarp",
	"Polska Dots Curtain",
	"Burn",
	"Fade",
	"Crosshatch",
	"CrossZoom",
	"Bow tie horizontal",
	"Simple zoom",
	"Zoom in circles",
	"Bow tie vertical",
	"Bounce",
	"Circle open",
	"Directional",
	"Circle crop",
	"Dreamy",
	"Cube",
	"Perlin",
	"Random squares",
	"Doorway",
	"Colour distance",
	"Polar function",
	"Dreamy zoom",
	"Stereo viewer",
	"Fade grayscale",
	"Circle",
	"Heart",
	"Grid flip",
	"Linear blur",
	"Doom screen transition",
	"Morph",
	"Luma",
	"Multiply blend",
	"Fade color",
	"Pin wheel",
	"Wind",
	"Window blinds",
	"Luminance melt",
	"Displacement",
	"Mosaic",
	"Fly eye",
	"Water drop",
	"Glitch memories",
	"Directional wipe",
	"Wipe up",
	"Squares wire",
	"Butterfly Wave Scrawler",
	"Kaleidoscope",
	"Wipe right",
	"Inverted page curl",
	"Pixelize",
	"Window slice",
	"Angular",
	"Ripple",
	"Crazy parametric fun",
	"Wipe left",
	"Rotate scale fade",
	"Glitch displace",
	"Colorphase",
	"Undulating burn out",
	"Swap",
	"Squeeze",
	"Cannabis leaf"
]
