name: build
on:
  push:
    branches:
    - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: 🔔 checkout
      uses: actions/checkout@v3

    - name: 🔧 setup bun
      uses: oven-sh/setup-bun@v2

    - name: 📦 install dependencies
      run: bun install --frozen-lockfile

    - name: 🔨 build
      run: bun run build
