
name: 📦 publish to npm
on:
  push:
    tags:
    - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    if: "! github.event.pull_request.head.repo.fork"
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
    - uses: actions/setup-node@v4
      with:
        node-version: "22"

    - run: bun install --frozen-lockfile
    - run: bun run build -s
    - run: bun run test

    - name: 🚀 npm publish
      uses: JS-DevTools/npm-publish@v3
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
